# Generated by Django 5.0.4 on 2024-04-20 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbilityScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strength", models.IntegerField()),
                ("dexterity", models.IntegerField()),
                ("constitution", models.IntegerField()),
                ("intelligence", models.IntegerField()),
                ("wisdom", models.IntegerField()),
                ("charisma", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ArmorProficiencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DamageDice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                ("sides", models.IntegerField()),
                ("mod", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DeathSaves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("successes", models.IntegerField()),
                ("failures", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("height", models.CharField(max_length=100)),
                ("weight", models.IntegerField()),
                ("eyes", models.CharField(max_length=100)),
                ("skin", models.CharField(max_length=100)),
                ("hair", models.CharField(max_length=100)),
                ("personality", models.CharField(max_length=100)),
                ("ideal", models.CharField(max_length=100)),
                ("bond", models.CharField(max_length=100)),
                ("flaw", models.CharField(max_length=100)),
                ("backstory", models.CharField(max_length=1024)),
                ("physical", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SavingThrows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strength", models.IntegerField()),
                ("dexterity", models.IntegerField()),
                ("constitution", models.IntegerField()),
                ("intelligence", models.IntegerField()),
                ("wisdom", models.IntegerField()),
                ("charisma", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Senses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("darkvision", models.IntegerField()),
                ("blindsight", models.IntegerField()),
                ("tremorsense", models.IntegerField()),
                ("truesight", models.IntegerField()),
                ("passive_perception", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acrobatics", models.IntegerField()),
                ("animal_handling", models.IntegerField()),
                ("arcana", models.IntegerField()),
                ("athletics", models.IntegerField()),
                ("deception", models.IntegerField()),
                ("history", models.IntegerField()),
                ("insight", models.IntegerField()),
                ("intimidation", models.IntegerField()),
                ("investigation", models.IntegerField()),
                ("medicine", models.IntegerField()),
                ("nature", models.IntegerField()),
                ("perception", models.IntegerField()),
                ("performance", models.IntegerField()),
                ("persuasion", models.IntegerField()),
                ("religion", models.IntegerField()),
                ("sleight_of_hand", models.IntegerField()),
                ("stealth", models.IntegerField()),
                ("survival", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("note", models.CharField(max_length=100)),
                ("href", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ToolProficiencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Treasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pp", models.IntegerField()),
                ("gp", models.IntegerField()),
                ("ep", models.IntegerField()),
                ("sp", models.IntegerField()),
                ("cp", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="WeaponProficiencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1024)),
                ("damage_bonus", models.IntegerField()),
                ("legendary", models.BooleanField()),
                ("reaction", models.BooleanField()),
                (
                    "damage_dice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.damagedice"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CombatStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("armor_class", models.IntegerField()),
                ("initiative", models.IntegerField()),
                ("speed", models.IntegerField()),
                ("hit_points", models.IntegerField()),
                ("hit_dice", models.CharField(max_length=100)),
                (
                    "death_saves",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.deathsaves"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subtype", models.CharField(max_length=100)),
                ("level", models.IntegerField()),
                ("hit_die", models.IntegerField()),
                ("spellcasting", models.CharField(max_length=100)),
                ("features", models.ManyToManyField(to="api.feature")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.source"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feature",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.source"
            ),
        ),
        migrations.CreateModel(
            name="Feat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1024)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("weight", models.IntegerField()),
                ("description", models.CharField(max_length=1024)),
                ("magic", models.BooleanField()),
                ("quantity", models.IntegerField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Background",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("option", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1024)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.IntegerField()),
                ("school", models.CharField(max_length=100)),
                ("casting_time", models.CharField(max_length=100)),
                ("range_area", models.CharField(max_length=100)),
                ("components", models.CharField(max_length=100)),
                ("material", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1024)),
                ("higher_level", models.CharField(max_length=1024)),
                ("ritual", models.BooleanField()),
                ("concentration", models.BooleanField()),
                ("attack_save", models.CharField(max_length=100)),
                ("damage_effect", models.CharField(max_length=100)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.source"
                    ),
                ),
                ("tags", models.ManyToManyField(to="api.tag")),
            ],
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1024)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subtype", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=100)),
                ("actions", models.ManyToManyField(to="api.action")),
                (
                    "senses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.senses"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.source"
                    ),
                ),
                ("traits", models.ManyToManyField(to="api.trait")),
            ],
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("weight", models.IntegerField()),
                ("description", models.CharField(max_length=1024)),
                ("attack_bonus", models.IntegerField()),
                ("damage_bonus", models.IntegerField()),
                ("damage_type", models.CharField(max_length=100)),
                (
                    "damage_dice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.damagedice"
                    ),
                ),
                ("properties", models.ManyToManyField(to="api.property")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("xp", models.IntegerField()),
                (
                    "ability_scores",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.abilityscores",
                    ),
                ),
                (
                    "armor_proficiencies",
                    models.ManyToManyField(to="api.armorproficiencies"),
                ),
                (
                    "background",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.background"
                    ),
                ),
                ("classes", models.ManyToManyField(to="api.class")),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.combatstats",
                    ),
                ),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.details"
                    ),
                ),
                ("equipment", models.ManyToManyField(to="api.equipment")),
                ("feats", models.ManyToManyField(to="api.feat")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.player"
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.race"
                    ),
                ),
                (
                    "saving_throws",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.savingthrows",
                    ),
                ),
                (
                    "skills",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.skills"
                    ),
                ),
                ("spells", models.ManyToManyField(to="api.spell")),
                (
                    "tool_proficiencies",
                    models.ManyToManyField(to="api.toolproficiencies"),
                ),
                (
                    "treasure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.treasure"
                    ),
                ),
                ("weapons", models.ManyToManyField(to="api.weapon")),
                (
                    "weapon_proficiencies",
                    models.ManyToManyField(to="api.weaponproficiencies"),
                ),
            ],
        ),
    ]
